/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import componentes.InfoProduto;
import controladores.ControladorCarrinho;
import controladores.ControladorEntidades;
import controladores.ControladorProduto;
import entidades.Funcionario;
import entidades.Produto;
import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jsouza
 */
public class TelaCompra extends javax.swing.JPanel {

    /**
     * Creates new form TelaCompra
     */
   
      Component frame = null;
      Produto prod;
    public TelaCompra() {
        initComponents();
        
        
        btn_voltar.setToolTipText("Para cancelar a compra solicite atendimento de um funcionário.");
        for(Produto produto : ControladorProduto.getInstance().produtos ){
            jPanel1.add(new InfoProduto(produto));
        }
            
    }
    public void mensagem(){
       JOptionPane.showMessageDialog(null, "O código do produto "+ prod.getNome() + " é: " + prod.getCodigo());
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_adicionar_cod = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        btn_carrinho = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 250, 250));

        btn_adicionar_cod.setBackground(new java.awt.Color(157, 114, 29));
        btn_adicionar_cod.setForeground(new java.awt.Color(250, 250, 250));
        btn_adicionar_cod.setText("Adicionar produto no carrinho");
        btn_adicionar_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionar_codActionPerformed(evt);
            }
        });

        btn_voltar.setBackground(new java.awt.Color(95, 0, 0));
        btn_voltar.setForeground(new java.awt.Color(250, 250, 250));
        btn_voltar.setText("Cancelar Compra");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_carrinho.setBackground(new java.awt.Color(52, 163, 55));
        btn_carrinho.setForeground(new java.awt.Color(250, 250, 250));
        btn_carrinho.setText("Carrinho");
        btn_carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carrinhoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new java.awt.GridLayout(2, 4, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btn_voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                        .addComponent(btn_adicionar_cod)
                        .addGap(18, 18, 18)
                        .addComponent(btn_carrinho))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 578, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_voltar)
                    .addComponent(btn_adicionar_cod)
                    .addComponent(btn_carrinho))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("painel");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adicionar_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionar_codActionPerformed
          String option = JOptionPane.showInputDialog("Digite o código de barras:");
           Produto produto = ControladorProduto.getInstance().getProdutoByCod(option);
        if (produto != null) {
            ControladorCarrinho.getInstance().adiciona(produto);
             JOptionPane.showMessageDialog(null, "Produto adicionado ao carrinho!");
             
        } else if (option != null) {
            JOptionPane.showMessageDialog(null, "Erro, produto não encontrado.");
        }
    }//GEN-LAST:event_btn_adicionar_codActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
       String option = JOptionPane.showInputDialog("Entre com o ID do funcionário:");
        Funcionario funcionario = ControladorEntidades.getInstance().getFuncionarioById(option);
        if (funcionario != null) {
            ControladorCarrinho.getInstance().clearItens();
            ((MainFrame) SwingUtilities.getWindowAncestor(this)).exibeTelaPrincipal();
        } else if (option != null) {
            JOptionPane.showMessageDialog(null, "Erro, funcionário não encontrado.");
        }
      
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_carrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carrinhoActionPerformed
        ((MainFrame) SwingUtilities.getWindowAncestor(this)).exibeTelaCarrinho();
    }//GEN-LAST:event_btn_carrinhoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar_cod;
    private javax.swing.JButton btn_carrinho;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
